SERVER_BASE_URL = 'http://localhost:3334'
CLIENT_HOST = 'localhost'
CREATE_GAME_NAME = 'GREETINGS PROFESSOR FALKEN'
CREATE_PLAYER_NAME = 'JOSHUA'
CREATE_PORT = 3332
JOIN_PLAYER_NAME = 'LIGHTMAN'
JOIN_PORT = 3333
